artifacts_root : artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Zeyadelgabbas/datasets/raw/refs/heads/main/samsumdata.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: facebook/bart-base
  transformed_path: artifacts/data_transformation/samsum_dataset_transformed

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/samsum_dataset_transformed
  model_ckpt: facebook/bart-base

  
model_evaluation:
  model_path: artifacts/model_trainer/pegasus-samsum-model
  data_path: artifacts/data_ingestion/samsum_dataset
  root_dir: artifacts/model_evaluation
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_filename: artifacts/model_evaluation/metrics.csv


