artifacts_root : artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Zeyadelgabbas/datasets/raw/refs/heads/main/samsumdata.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail
  transformed_path: artifacts/data_transformation/samsum_dataset_transformed
